import type { Metadata } from "next";
import "./globals.css";
import { Lexend } from "next/font/google";
import { PrivyWrapper } from "@/components/providers/PrivyWrapper";

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <PrivyWrapper>
      <body
        className={`${lexend.className} antialiased`}
      >
        {children}
      </body>
    </PrivyWrapper>
    </html>
  );
}
